default_context:
  project_name: 'ioctl'
  project_slug: 'ioctl'
  domain_main: 'ioctl.com'
  domain_staging: 'stag.ioctl.com'
  docker_swarm_stack_name_main: 'ioctl-com'
  docker_swarm_stack_name_staging: 'stag-ioctl-com'
  secret_key: 'changethis'
  first_superuser: 'admin@ioctl.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.ioctl.com", "https://stag.ioctl.com", "https://ioctl.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@ioctl.com'
  postgres_password: 'the_app_user'
  pgadmin_default_user: 'app-user'
  pgadmin_default_user_password: 'the_app_user'
  traefik_constraint_tag: 'ioctl.com'
  traefik_constraint_tag_staging: 'stag.ioctl.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
